INSERT INTO tb_metodo(ID,METODO) VALUES (1,'BOLETO');
INSERT INTO tb_metodo(ID,METODO) VALUES (2,'PIX');
INSERT INTO tb_metodo(ID,METODO) VALUES (3,'CARTAO_CREDITO');
INSERT INTO tb_metodo(ID,METODO) VALUES (4,'CARTAO_DEBITO');

--INSERT INTO tb_payment(ID,CODIGO_DEBITO,CPF_CNPJ,NUMERO_CARTAO,VALOR_PAGAMENTO,METODO_ID,STATUS) VALUES (1,1234,'01755127286','123465',123.23,1,'AGUARDANDO_PROCESSAMENTO');
